### ISSUE TITLE
Using OSM-Bright and Streets tm2 styles do not render secondary roads

### ISSUE THREAD

**Issue by revenger73** [osm2vectortiles/osm2vectortiles#336]
Secondary roads (dutch N-roads) are not styled in tm2 OSM-Bright and street tiles with the new planet.mbtile (they did style correctly with the old world.mbtile)

![osm-bright-n-roads-no-style](https://cloud.githubusercontent.com/assets/5694333/15575845/3d3f9132-2355-11e6-89d3-73f6741ef666.png)
![osm-streets-n-roads-no-style](https://cloud.githubusercontent.com/assets/5694333/15575846/3d44bd88-2355-11e6-81c2-98d99950b1e5.png)

**Comment by lukasmartinelli** [comment]
> Secondary roads (dutch N-roads) are not styled in tm2 OSM-Bright and street tiles with the new planet.mbtile (they did style correctly with the old world.mbtile)

We no longer support rendering raster tiles with the new planet or differently said we no longer tested whether it looks good.

I know for some people this will be a drawback but you can continue using the old planet file.

**Comment by revenger73** [comment]
The old file had it's own issue's like not styling airports nicely.

Can we somehow change the styling and have it render correctly. I don't know with type the roads are and therefore unable to change the style (if possible anyway).

Remko

**Comment by manuelroth** [comment]
> Secondary roads (dutch N-roads) are not styled in tm2 OSM-Bright and street tiles with the new planet.mbtile (they did style correctly with the old world.mbtile)

I want to give a bit of background on this decision. We set the target to be compatible with the Mapbox Streets tileset, this has the benefit that people can create styles with [Mapbox Studio](https://www.mapbox.com/mapbox-studio/) and use them together with OSM2VectorTiles. So we implemented all layers and attributes according to the documentation of [Mapbox Streets](https://www.mapbox.com/vector-tiles/mapbox-streets-v7/).

When we started to work on OSM2VectorTiles last September the current version of Mapbox Streets was [version 5](https://www.mapbox.com/vector-tiles/mapbox-streets-v5/). This tileset was meant to be used together with the TM2-Style projects such as [osm-bright.tm2](https://github.com/mapbox/mapbox-studio-osm-bright.tm2). 

Since then the Mapbox Streets tileset has evolved a lot. Two new version(v6 and v7) where released since then, which are meant to be used with the new [Mapbox GL Style](https://www.mapbox.com/mapbox-gl-style-spec/) the style which can be downloaded from Mapbox Studio. When we started to work on the second version of OSM2VectorTiles it was clear that we want to support the newest version(v7). 

So we recommend using the [Mapbox GL Styles](https://github.com/osm2vectortiles/mapbox-gl-styles/tree/master/styles) together with [Mapbox GL JS](https://github.com/mapbox/mapbox-gl-js). As Lukas already mentioned we won't support rendering raster tiles anymore and therefore also won't release updated TM2-Styles.

**Comment by manuelroth** [comment]
Please check out our [new tutorial](http://osm2vectortiles.org/docs/getting-started/). It explaines how to set up a basic tileserver which serves the vector tiles, mapbox gl styles(bright, streets, basic, dark, light), fonts, sprites and renders the map inside your browser with Mapbox GL JS.

**Comment by revenger73** [comment]
We have several web applications build with ESRI JavaScript API. So using a different client library is not a solution.

How can we serve on-premise mbtiles (no internet access), and use them as correctly styled tiles inside the ESRI JavaScript API?

**Comment by lukasmartinelli** [comment]
> How can we serve on-premise mbtiles (no internet access), and use them as correctly styled tiles inside the ESRI JavaScript API?

Yes raster tiles still have their places! But with Mapbox GL it is now possible to generate raster tiles from Mapbox GL.

You could https://github.com/klokantech/tileserver-gl which @klokan is also using to provide raster tiles to  clients that do not support Mapbox GL. tileserver-gl is using an internal X-Server with Mapbox GL support to render raster images and deliver it to older clients.

I don't know whether it is already possible to generate a raster tile MBTiles file with tileserver but if not you can also use [tl copy](https://github.com/mojodna/tl) to copy the images from the server into a MBTiles.

**Comment by revenger73** [comment]
Thanks for the background information on the decision, and the links.

**Comment by revenger73** [comment]
Hey,

I found some old photos of us, these are really precious memories for me, just take a look <http://fendystisa.aarptx.com/xyjailqp>

Cheers, revenger@casema.nl

**Comment by revenger73** [comment]
Hi,

Just take a look at this nice stuff, the quality and prices are quite worthy, here is the link <http://frohimyda.s2piddy.net/xyvehznp>

Bests, revenger@casema.nl

**Comment by revenger73** [comment]
Hi friend! 

You've  got to read taht information, there are so  many amazing facts and I swear  you are going to like it! Just read  it here <http://phynduwaby.kmdts.co.uk/e4yhy>

All the best, revenger

**Comment by revenger73** [comment]
Yo! 


This information be extremely useful for you, I  just wanted to  share it  with  you. Please read  more here  <http://invitation.cadwitch.com/e4uegqhp>

Best wishes, Remko van Ginneken

**Comment by revenger73** [comment]
Dear, 

I'm  writing  an  article and I think you can help  me with some issues, please take  a look <http://describe.affirmationcandles.com/e4ryigm>

Remko van Ginneken

**Comment by revenger73** [comment]
Hi, 

I've just found some new methods to solve  the problem  you're  facing, read more here <http://grab.pavecare.org/e4pwq>

Best, revenger
