### ISSUE TITLE
Remove unnecessary roads at lower zoom levels

### ISSUE THREAD

**Issue by lukasmartinelli** [osm2vectortiles/osm2vectortiles#86]
We can save alot of space #77 if we filter the roads better.

**Comment by sfkeller** [comment]
This filtering obviously can be accomplished using ST_SimplifyPreserveTopology.

Question: At "Zoom Layer Reference" http://osm2vectortiles.org/docs/layer-reference/ it's indicated that roads are included starting with zoom level 5. I think this could be true but at least in the raster version, roads are not shown: http://klokantech-3.tileserver.com/osm-bright/5/16/11.png . Why?

**Comment by lukasmartinelli** [comment]
> Question: At "Zoom Layer Reference" http://osm2vectortiles.org/docs/layer-reference/ it's indicated that roads are included starting with zoom level 5. I think this could be true but at least in the raster version, roads are not shown: http://klokantech-3.tileserver.com/osm-bright/5/16/11.png . Why?

The zoom level table is for the data in the vector tiles not the rendered end product. 


Alot of styles also define certain zoom levels at which data appears. It is not uncommon that you only show data at closer zoom levels and not when it is already available.

```css
#roads [zoom >= 6] {
// my style definitions
}
```

**Comment by sfkeller** [comment]
I'm aware that you don't have to show data when it is available. I was just wondering why that is the case here, since both stylings - raster/Mapnik-rendered and vector/MapboxGL rendered - are called "OSM Bright" and because I am looking for ways to reduce vector tile size.

**Comment by lukasmartinelli** [comment]
> I was just wondering why that is the case here, since both stylings - raster/Mapnik-rendered and vector/MapboxGL rendered - are called "OSM Bright"

The decision to where which layers should be shown was taken straight from Mapbox. @manuelroth went through the Mapbox Streets zoom levels and figured out which layers appear on which zoom level.

> because I am looking for ways to reduce vector tile size.

I think simplifying the roads should help decreasing the size. We somehow forgot to generalize the roads at lower zoom levels - we had it at one point in time.
But the big difference lays in the **number of road labels** we have.

Perhaps the simplifying can also solve the problems with many road parts like e.g. main roads (where some parts are not main roads and therefore there is no line at all but it would look better if it was just a straight line for styling even if it is not true).

![schweizerkarte___mapbox](https://cloud.githubusercontent.com/assets/1288339/11918690/11416302-a73c-11e5-8b5a-70ea9ecd341a.png)

**Comment by lukasmartinelli** [comment]
I think this looks solved as of today @manuelroth?
Size reduction indicates that we got the bad boy that made the tiles too big #266.

![](https://media.giphy.com/media/ID4NXWnwuLnLq/giphy.gif)

**Comment by manuelroth** [comment]
haha yes I think so.

**Comment by klokan** [comment]
+1 :-)

**Comment by isimonescu** [comment]
Maybe this bug still alive? Please see https://github.com/osm2vectortiles/osm2vectortiles/issues/439.
